blank_issues_enabled: false
contact_links:
  - name: ğŸ“¬ Contact interne
    url: https://github.com/teremuhamblin/La-RST
    about: Pour toute demande interne ou confidentielle, contactez les responsables.
